### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WizardGoose** [symt/BazaarNotifier#124]
Can't find a way to replicate the crash, it just happens often:

```
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.3+7380-for-MC-1.8.9.jar)
  AsmHelperLoadingPlugin (ctjs-2.2.0-1.8.9.jar)
  PatcherTweaker (Patcher-1.8.7 (1.8.9).jar)
  Skytils On Top (Skytils-1.8.1.jar)
  ModTweaker (Patcher-1.8.7 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 12/02/24 6:42 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at dev.meyi.bn.modules.module.NotificationModule.draw(NotificationModule.java:102)
	at dev.meyi.bn.modules.ModuleList.drawAllGui(ModuleList.java:92)
	at dev.meyi.bn.handlers.ChestTickHandler.renderInChest(ChestTickHandler.java:234)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_290_ChestTickHandler_renderInChest_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:595)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:72)
	at net.minecraft.client.gui.inventory.GuiChest.drawScreen(SourceFile)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1436)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.run(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:173)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:117)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at dev.meyi.bn.modules.module.NotificationModule.draw(NotificationModule.java:102)
	at dev.meyi.bn.modules.ModuleList.drawAllGui(ModuleList.java:92)
	at dev.meyi.bn.handlers.ChestTickHandler.renderInChest(ChestTickHandler.java:234)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_290_ChestTickHandler_renderInChest_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:595)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:72)
	at net.minecraft.client.gui.inventory.GuiChest.drawScreen(SourceFile)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiChest
	Mouse location: Scaled: (480, 269). Absolute: (960, 540)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 23 total; [EntityPlayerSP['GhostyGoose_'/1451329, l='MpServer', x=-31.31, y=200.00, z=-121.44], EntityOtherPlayerMP['thebestdude671'/1444100, l='MpServer', x=-51.68, y=200.00, z=-121.21], EntityOtherPlayerMP['Frank226011'/1437177, l='MpServer', x=-48.50, y=200.00, z=-121.50], EntityOtherPlayerMP['Washeroom'/1450753, l='MpServer', x=57.33, y=201.33, z=-112.45], EntityOtherPlayerMP['AestheticShrimp'/1451330, l='MpServer', x=-31.31, y=210.91, z=-121.47], EntityOtherPlayerMP['Treasuer Hunter'/1409106, l='MpServer', x=-78.72, y=187.00, z=-68.50], EntityOtherPlayerMP['Prylar'/1440573, l='MpServer', x=19.32, y=149.74, z=-51.33], EntityOtherPlayerMP['TwoRepublics'/1450024, l='MpServer', x=26.69, y=153.00, z=-60.00], EntityOtherPlayerMP['PomInu'/1437858, l='MpServer', x=-22.42, y=152.16, z=-44.66], EntityOtherPlayerMP['Jky0'/1447843, l='MpServer', x=-115.50, y=207.00, z=-52.50], EntityOtherPlayerMP['Alternate01377'/1428554, l='MpServer', x=-126.13, y=173.00, z=-74.94], EntityOtherPlayerMP['xqv3d60504'/72, l='MpServer', x=-10.50, y=201.00, z=-103.50], EntityOtherPlayerMP['ie68100kne'/73, l='MpServer', x=-15.50, y=201.00, z=-98.50], EntityOtherPlayerMP['3vtq12a53i'/79, l='MpServer', x=-37.50, y=200.00, z=-131.50], EntityOtherPlayerMP['98kkr947u8'/94, l='MpServer', x=-45.50, y=200.00, z=-124.50], EntityOtherPlayerMP['5q18g9ej9t'/95, l='MpServer', x=-45.50, y=200.00, z=-118.50], EntityOtherPlayerMP['4f6new6qjt'/133, l='MpServer', x=-38.00, y=200.00, z=-119.00], EntityOtherPlayerMP['kj13p19zgj'/100, l='MpServer', x=-30.00, y=214.00, z=-89.00], EntityOtherPlayerMP['zadokmw'/1428252, l='MpServer', x=67.22, y=208.50, z=-26.34], EntityOtherPlayerMP['BadOmensz'/1358826, l='MpServer', x=85.50, y=198.00, z=-97.50], EntityOtherPlayerMP['AlexHayato'/1442890, l='MpServer', x=83.91, y=199.00, z=-112.50], EntityOtherPlayerMP['1m1785bo2s'/6, l='MpServer', x=5.38, y=200.00, z=-109.22], EntityOtherPlayerMP['Treasuer Hunter'/1452109, l='MpServer', x=-107.50, y=206.00, z=-60.50]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -49.00,200.00,-122.00 - World: (-49,200,-122), Chunk: (at 15,12,6 in -4,-8; contains blocks -64,0,-128 to -49,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 256409864 game time, 818914 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 122 total; [EntityVillager['Villager'/5, l='MpServer', x=-6.50, y=201.00, z=-154.50], EntityOtherPlayerMP['1m1785bo2s'/6, l='MpServer', x=5.38, y=200.00, z=-109.22], EntityOtherPlayerMP['AestheticShrimp'/1451330, l='MpServer', x=-31.31, y=210.91, z=-121.47], EntityArmorStand['Armor Stand'/8, l='MpServer', x=42.44, y=183.03, z=-43.34], EntityArmorStand['Armor Stand'/9, l='MpServer', x=42.41, y=183.03, z=-41.69], EntityOtherPlayerMP['zadokmw'/1428252, l='MpServer', x=67.22, y=208.50, z=-26.34], EntityArmorStand['Armor Stand'/523, l='MpServer', x=-22.50, y=151.00, z=-79.50], EntityArmorStand['Armor Stand'/14092, l='MpServer', x=13.50, y=201.00, z=-148.50], EntityArmorStand['Armor Stand'/524, l='MpServer', x=-22.50, y=150.75, z=-79.50], EntityArmorStand['Armor Stand'/14093, l='MpServer', x=13.50, y=200.75, z=-148.50], EntityArmorStand['Armor Stand'/525, l='MpServer', x=23.50, y=151.00, z=-57.50], EntityArmorStand['Armor Stand'/14094, l='MpServer', x=-6.50, y=201.09, z=-154.50], EntityArmorStand['Armor Stand'/526, l='MpServer', x=23.50, y=150.75, z=-57.50], EntityArmorStand['Armor Stand'/14, l='MpServer', x=40.50, y=208.00, z=-106.50], EntityArmorStand['Armor Stand'/14095, l='MpServer', x=-6.50, y=200.84, z=-154.50], EntityArmorStand['Armor Stand'/527, l='MpServer', x=-2.50, y=149.25, z=-68.50], EntityArmorStand['Armor Stand'/15, l='MpServer', x=38.50, y=208.00, z=-106.50], EntityArmorStand['Armor Stand'/528, l='MpServer', x=-2.50, y=149.00, z=-68.50], EntityArmorStand['Armor Stand'/16, l='MpServer', x=38.50, y=208.00, z=-106.50], EntityArmorStand['Armor Stand'/529, l='MpServer', x=-2.50, y=148.75, z=-68.50], EntityArmorStand['Armor Stand'/17, l='MpServer', x=40.50, y=208.00, z=-106.50], EntityOtherPlayerMP['thebestdude671'/1444100, l='MpServer', x=-51.68, y=200.00, z=-121.21], EntityArmorStand['Armor Stand'/530, l='MpServer', x=23.50, y=151.00, z=-87.50], EntityArmorStand['Armor Stand'/531, l='MpServer', x=23.50, y=150.75, z=-87.50], EntityOtherPlayerMP['Treasuer Hunter'/1409106, l='MpServer', x=-78.72, y=187.00, z=-68.50], EntityOtherPlayerMP['Washeroom'/1450753, l='MpServer', x=57.33, y=201.33, z=-112.45], EntityXPOrb['Experience Orb'/1426703, l='MpServer', x=-36.75, y=173.00, z=-66.00], EntityArmorStand['Armor Stand'/1821, l='MpServer', x=35.00, y=202.00, z=-146.00], EntityArmorStand['Armor Stand'/1822, l='MpServer', x=35.00, y=201.75, z=-146.00], EntityOtherPlayerMP['Prylar'/1440573, l='MpServer', x=19.32, y=149.74, z=-51.33], EntityOtherPlayerMP['TwoRepublics'/1450024, l='MpServer', x=26.69, y=153.00, z=-60.00], EntityArmorStand['Armor Stand'/1058, l='MpServer', x=34.00, y=202.00, z=-141.00], EntityArmorStand['Armor Stand'/1059, l='MpServer', x=34.00, y=201.75, z=-141.00], EntityArmorStand['Armor Stand'/14116, l='MpServer', x=29.00, y=202.00, z=-149.00], EntityArmorStand['Armor Stand'/14117, l='MpServer', x=29.00, y=201.75, z=-149.00], EntityArmorStand['Armor Stand'/21031, l='MpServer', x=-30.00, y=214.00, z=-89.00], EntityArmorStand['Armor Stand'/21032, l='MpServer', x=-30.00, y=213.75, z=-89.00], EntityOtherPlayerMP['Prylar'/1440573, l='MpServer', x=19.32, y=149.74, z=-51.33], EntityArmorStand['Armor Stand'/43, l='MpServer', x=-11.50, y=202.00, z=-98.50], EntityArmorStand['Armor Stand'/44, l='MpServer', x=-9.59, y=200.59, z=-102.28], EntityArmorStand[' 6Emissary Eliza'/557, l='MpServer', x=-37.50, y=200.00, z=-131.50], EntityArmorStand['Armor Stand'/45, l='MpServer', x=-9.28, y=200.41, z=-100.91], EntityArmorStand[' e lCLICK'/558, l='MpServer', x=-37.50, y=199.75, z=-131.50], EntityArmorStand['Armor Stand'/46, l='MpServer', x=-9.44, y=200.38, z=-101.88], EntityArmorStand[' 6Royal Guard'/559, l='MpServer', x=-45.50, y=200.00, z=-124.50], EntityItemFrame['entity.ItemFrame.name'/47, l='MpServer', x=-13.03, y=201.50, z=-105.50], EntityOtherPlayerMP['Treasuer Hunter'/1451245, l='MpServer', x=-104.53, y=206.00, z=-54.94], EntityArmorStand[' e lCLICK'/560, l='MpServer', x=-45.50, y=199.75, z=-124.50], EntityItemFrame['entity.ItemFrame.name'/48, l='MpServer', x=-9.50, y=201.50, z=-105.97], EntityArmorStand[' aGuide'/561, l='MpServer', x=-38.00, y=200.38, z=-119.00], EntityItemFrame['entity.ItemFrame.name'/49, l='MpServer', x=-8.03, y=202.50, z=-104.50], EntityArmorStand['Rhys'/562, l='MpServer', x=-38.00, y=200.00, z=-119.00], EntityArmorStand['Armor Stand'/50, l='MpServer', x=-12.50, y=202.00, z=-97.50], EntityArmorStand['Armor Stand'/14130, l='MpServer', x=35.00, y=202.00, z=-150.00], EntityArmorStand[' e lCLICK'/563, l='MpServer', x=-38.00, y=199.75, z=-119.00], EntityArmorStand['Armor Stand'/14131, l='MpServer', x=35.00, y=201.75, z=-150.00], EntityArmorStand[' 6Royal Guard'/564, l='MpServer', x=-45.50, y=200.00, z=-118.50], EntityArmorStand[' e lCLICK'/565, l='MpServer', x=-45.50, y=199.75, z=-118.50], EntityArmorStand['Armor Stand'/573, l='MpServer', x=-15.50, y=201.00, z=-98.50], EntityArmorStand['Armor Stand'/574, l='MpServer', x=-15.50, y=200.75, z=-98.50], EntityOtherPlayerMP['TwoRepublics'/1450024, l='MpServer', x=26.69, y=153.00, z=-60.00], EntityArmorStand['Armor Stand'/575, l='MpServer', x=-10.50, y=201.00, z=-103.50], EntityArmorStand['Armor Stand'/576, l='MpServer', x=-10.50, y=200.75, z=-103.50], EntityArmorStand['Armor Stand'/577, l='MpServer', x=5.41, y=200.25, z=-109.22], EntityOtherPlayerMP['Laxsterr'/1382379, l='MpServer', x=47.50, y=202.84, z=-78.88], EntityArmorStand['Armor Stand'/578, l='MpServer', x=5.41, y=200.00, z=-109.22], EntityArmorStand['Armor Stand'/579, l='MpServer', x=5.41, y=199.75, z=-109.22], EntityArmorStand['Armor Stand'/580, l='MpServer', x=38.50, y=201.00, z=-86.50], EntityArmorStand['Armor Stand'/581, l='MpServer', x=38.50, y=200.75, z=-86.50], EntityOtherPlayerMP['Treasuer Hunter'/1409106, l='MpServer', x=-78.72, y=187.00, z=-68.50], EntityOtherPlayerMP['PomInu'/1437858, l='MpServer', x=-22.42, y=152.16, z=-44.66], EntityOtherPlayerMP['xqv3d60504'/72, l='MpServer', x=-10.50, y=201.00, z=-103.50], EntityOtherPlayerMP['ie68100kne'/73, l='MpServer', x=-15.50, y=201.00, z=-98.50], EntityOtherPlayerMP['Treasuer Hunter'/1451247, l='MpServer', x=-117.50, y=203.00, z=-45.50], EntityOtherPlayerMP['Jky0'/1447843, l='MpServer', x=-115.50, y=207.00, z=-52.50], EntityOtherPlayerMP['Alternate01377'/1428554, l='MpServer', x=-126.13, y=173.00, z=-74.94], EntityOtherPlayerMP['3vtq12a53i'/79, l='MpServer', x=-37.50, y=200.00, z=-131.50], EntityArmorStand['Armor Stand'/1451334, l='MpServer', x=-31.91, y=200.37, z=-121.47], EntityArmorStand[' 8[ 7Lv100 8]  6GhostyGoose_'s Bal d ?'/1451335, l='MpServer', x=-31.94, y=201.18, z=-120.84], EntityOtherPlayerMP['AestheticShrimp'/1451330, l='MpServer', x=-31.31, y=210.91, z=-121.47], EntityArmorStand['Armor Stand'/602, l='MpServer', x=-79.50, y=200.00, z=-123.50], EntityArmorStand['Armor Stand'/603, l='MpServer', x=-79.50, y=199.75, z=-123.50], EntityOtherPlayerMP['Treasuer Hunter'/1452109, l='MpServer', x=-107.50, y=206.00, z=-60.50], EntityOtherPlayerMP['AlexHayato'/1442890, l='MpServer', x=83.91, y=199.00, z=-112.50], EntityXPOrb['Experience Orb'/1429067, l='MpServer', x=-64.75, y=169.00, z=-56.25], EntityOtherPlayerMP['98kkr947u8'/94, l='MpServer', x=-45.50, y=200.00, z=-124.50], EntityOtherPlayerMP['Alternate01377'/1428554, l='MpServer', x=-126.13, y=173.00, z=-74.94], EntityOtherPlayerMP['5q18g9ej9t'/95, l='MpServer', x=-45.50, y=200.00, z=-118.50], EntityOtherPlayerMP['kj13p19zgj'/100, l='MpServer', x=-30.00, y=214.00, z=-89.00], EntityArmorStand['Armor Stand'/886, l='MpServer', x=-22.50, y=151.00, z=-49.50], EntityArmorStand['Armor Stand'/887, l='MpServer', x=-22.50, y=150.75, z=-49.50], EntityOtherPlayerMP['xqv3d60504'/72, l='MpServer', x=-10.50, y=201.00, z=-103.50], EntityOtherPlayerMP['ie68100kne'/73, l='MpServer', x=-15.50, y=201.00, z=-98.50], EntityOtherPlayerMP['3vtq12a53i'/79, l='MpServer', x=-37.50, y=200.00, z=-131.50], EntityOtherPlayerMP['98kkr947u8'/94, l='MpServer', x=-45.50, y=200.00, z=-124.50], EntityOtherPlayerMP['5q18g9ej9t'/95, l='MpServer', x=-45.50, y=200.00, z=-118.50], EntityOtherPlayerMP['1853u7adw1'/109, l='MpServer', x=-79.50, y=200.00, z=-123.50], EntityOtherPlayerMP['4f6new6qjt'/133, l='MpServer', x=-38.00, y=200.00, z=-119.00], EntityOtherPlayerMP['kj13p19zgj'/100, l='MpServer', x=-30.00, y=214.00, z=-89.00], EntityOtherPlayerMP['4f6new6qjt'/133, l='MpServer', x=-38.00, y=200.00, z=-119.00], EntityOtherPlayerMP['zadokmw'/1428252, l='MpServer', x=67.22, y=208.50, z=-26.34], EntityXPOrb['Experience Orb'/1418907, l='MpServer', x=-60.84, y=166.00, z=-52.06], EntityXPOrb['Experience Orb'/1452211, l='MpServer', x=-126.75, y=173.73, z=-76.75], EntityArmorStand['Armor Stand'/179, l='MpServer', x=-8.50, y=228.53, z=-134.50], EntityXPOrb['Experience Orb'/1429158, l='MpServer', x=-64.75, y=170.00, z=-58.66], EntityOtherPlayerMP['Jky0'/1447843, l='MpServer', x=-115.50, y=207.00, z=-52.50], EntityOtherPlayerMP['PomInu'/1437858, l='MpServer', x=-22.42, y=152.16, z=-44.66], EntityArmorStand['Armor Stand'/11704, l='MpServer', x=43.50, y=177.00, z=-42.50], EntityOtherPlayerMP['BadOmensz'/1358826, l='MpServer', x=85.50, y=198.00, z=-97.50], EntityArmorStand['Armor Stand'/11705, l='MpServer', x=43.50, y=176.75, z=-42.50], EntityOtherPlayerMP['AlexHayato'/1442890, l='MpServer', x=83.91, y=199.00, z=-112.50], EntityArmorStand['Armor Stand'/188, l='MpServer', x=-20.50, y=206.53, z=-58.50], EntityOtherPlayerMP['Treasuer Hunter'/1452109, l='MpServer', x=-107.50, y=206.00, z=-60.50], EntityOtherPlayerMP['1m1785bo2s'/6, l='MpServer', x=5.38, y=200.00, z=-109.22], EntityPlayerSP['GhostyGoose_'/1451329, l='MpServer', x=-31.31, y=200.00, z=-121.44], EntityArmorStand['Armor Stand'/32736, l='MpServer', x=-3.50, y=149.00, z=-108.50], EntityArmorStand['Armor Stand'/32737, l='MpServer', x=-3.50, y=148.75, z=-108.50], EntityOtherPlayerMP['thebestdude671'/1444100, l='MpServer', x=-51.68, y=200.00, z=-121.21], EntityOtherPlayerMP['Frank226011'/1437177, l='MpServer', x=-48.50, y=200.00, z=-121.50], EntityOtherPlayerMP['Frank226011'/1437177, l='MpServer', x=-48.50, y=200.00, z=-121.50], EntityOtherPlayerMP['Washeroom'/1450753, l='MpServer', x=57.33, y=201.33, z=-112.45], EntityOtherPlayerMP['BadOmensz'/1358826, l='MpServer', x=85.50, y=198.00, z=-97.50]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (2024.1.9.9) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:402)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.run(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:173)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:117)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Game Directory: C:\Users\ihate\AppData\Roaming\.minecraft
	ChatTriggers modules: [Module{name=axios,version=1.0.9}, Module{name=BeaconBeam,version=1.0.1}, Module{name=ChatCoords,version=0.0.2}, Module{name=Coleweight,version=1.11.9}, Module{name=Elementa,version=1.5.2}, Module{name=guimanager,version=0.1.7}, Module{name=PogData,version=1.0.2}, Module{name=PromiseV2,version=1.0.4}, Module{name=requestV2,version=2.0.2}, Module{name=soopyAddonsData,version=0.0.1}, Module{name=soopyApis,version=0.1.17}, Module{name=SoopyV2,version=2.1.202}, Module{name=Vigilance,version=1.3.2}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1098183080 bytes (1047 MB) / 2266497024 bytes (2161 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version        | Source                                     |
	| ------ | -------------------- | -------------- | ------------------------------------------ |
	| UCHIJA | mcp                  | 9.19           | minecraft.jar                              |
	| UCHIJA | FML                  | 8.0.99.99      | forge-1.8.9-11.15.1.2318-1.8.9.jar         |
	| UCHIJA | Forge                | 11.15.1.2318   | forge-1.8.9-11.15.1.2318-1.8.9.jar         |
	| UCHIJA | essential            | 1.0.0          | Essential (forge_1.8.9).jar                |
	| UCHIJA | oneconfig            | 0.2.2-alpha191 | OneConfig (1.8.9-forge).jar                |
	| UCHIJA | BazaarNotifier       | 1.7.0          | BazaarNotifier-1.7.0.jar                   |
	| UCHIJA | chattriggers         | 2.2.0          | ctjs-2.2.0-1.8.9.jar                       |
	| UCHIJA | hyblockrnganalyzer   | 1.7.4          | hyblockrnganalyzer-1.7.4.jar               |
	| UCHIJA | LunatriusCore        | 1.1.2.32       | LunatriusCore-1.8.9-1.1.2.32-universal.jar |
	| UCHIJA | notenoughupdates     | 2.1.1-PRE      | NotEnoughUpdates-2.1.1-Alpha-26.jar        |
	| UCHIJA | patcher              | 1.8.7          | Patcher-1.8.7 (1.8.9).jar                  |
	| UCHIJA | text_overflow_scroll | 1.4.0          | Scrollable Tooltips-1.4 (1.8.9).jar        |
	| UCHIJA | skyblockaddons       | 1.7.3          | SkyblockAddons-1.7.3+7380-for-MC-1.8.9.jar |
	| UCHIJA | SkyblockExtras       | 2.2.0-pre17    | SkyblockExtras-2.2.0-pre17-RELEASE.jar     |
	| UCHIJA | skytils              | 1.8.1          | Skytils-1.8.1.jar                          |
	| UCHIJA | soopyv2forge         | 1.1            | soopyv2forge-1.1.jar                       |

	Loaded coremods (and transformers): 
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.3+7380-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
AsmHelperLoadingPlugin (ctjs-2.2.0-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
PatcherTweaker (Patcher-1.8.7 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
Skytils On Top (Skytils-1.8.1.jar)
  gg.skytils.skytilsmod.asm.SkytilsTransformer
ModTweaker (Patcher-1.8.7 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: no fire.zip,  aFurfSky Reborn  8 lFULL 8.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 546.33
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**Comment by symt** [comment]
#123
