### ISSUE TITLE
Gemstone orders aren't registered

### ISSUE THREAD

**Issue by symt** [symt/BazaarNotifier#53]
This is the investigation issue for the bug

**Comment by symt** [comment]
```
java.util.concurrent.ExecutionException: dev.meyi.repack.org.json.JSONException: JSONObject[" Fine Jade Gemstone"] not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:20) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: dev.meyi.repack.org.json.JSONException: JSONObject[" Fine Jade Gemstone"] not found.
	at dev.meyi.repack.org.json.JSONObject.get(JSONObject.java:572) ~[JSONObject.class:?]
	at dev.meyi.repack.org.json.JSONObject.getString(JSONObject.java:859) ~[JSONObject.class:?]
	at dev.meyi.bn.handlers.EventHandler.bazaarChatHandler(EventHandler.java:33) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_EventHandler_bazaarChatHandler_ClientChatReceivedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onClientChat(ForgeEventFactory.java:272) ~[ForgeEventFactory.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:753) ~[bcy.class:?]
	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:44) ~[fy.class:?]
	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:9) ~[fy.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:19) ~[g.class:?]
	... 9 more
```

Now we need an example of the message without the mod to see why.

**Comment by symt** [comment]
![image](https://user-images.githubusercontent.com/28537235/134815700-41e19c1e-36f6-4feb-8dfe-df631d9f69c7.png)

**Comment by symt** [comment]
Found the issue

The `stripString` method in the Utils class clears out all characters outside a character range (20-127) which means the symbols are removed, causing the bug. The method probably shouldn't be used anyways.
