### ISSUE TITLE
dev.meyi.repack.org.json.JSONException: JSONArray[0] not found.

### ISSUE THREAD

**Issue by curather** [symt/BazaarNotifier#60]
dev.meyi.repack.org.json.JSONException: JSONArray[0] not found.
	at dev.meyi.repack.org.json.JSONArray.get(JSONArray.java:225)
	at dev.meyi.repack.org.json.JSONArray.getJSONObject(JSONArray.java:438)
	at dev.meyi.bn.utilities.EnchantedCraftingHandler.getBestEnchantRecipes(EnchantedCraftingHandler.java:24)
	at dev.meyi.bn.modules.CraftingModule.draw(CraftingModule.java:36)
	at dev.meyi.bn.modules.ModuleList.drawAllModules(ModuleList.java:54)
	at dev.meyi.bn.handlers.EventHandler.renderBazaarEvent(EventHandler.java:144)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_EventHandler_renderBazaarEvent_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:595)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:72)
	at net.minecraft.client.gui.inventory.GuiChest.drawScreen(SourceFile)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1436)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.run(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

------------------------------
Here is the fix
EnchantedCraftingHandler.java
Starting at Line 21, move the material declaration from line 23 to 22 right before the if.  then add ` &&
                    BazaarNotifier.bazaarDataRaw.getJSONObject(material).getJSONArray("sell_summary").length() > 0 && BazaarNotifier.bazaarDataRaw.getJSONObject(material).getJSONArray("buy_summary").length() > 0` into the if statement.

It should look like 
`String material = BazaarNotifier.enchantCraftingList.getJSONObject("normal").getJSONObject(itemName).getString("material");
            if(BazaarNotifier.bazaarDataRaw.getJSONObject(itemName).getJSONArray("sell_summary").length() > 0 && BazaarNotifier.bazaarDataRaw.getJSONObject(itemName).getJSONArray("buy_summary").length() > 0 &&
                    BazaarNotifier.bazaarDataRaw.getJSONObject(material).getJSONArray("sell_summary").length() > 0 && BazaarNotifier.bazaarDataRaw.getJSONObject(material).getJSONArray("buy_summary").length() > 0) {
                double price1 = (BazaarNotifier.bazaarDataRaw.getJSONObject(itemName).getJSONArray("sell_summary").getJSONObject(0).getDouble("pricePerUnit")) - (BazaarNotifier.bazaarDataRaw.getJSONObject(material).getJSONArray("sell_summary").getJSONObject(0).getDouble("pricePerUnit")) * 160;
                double price2 = BazaarNotifier.bazaarDataRaw.getJSONObject(itemName).getJSONArray("buy_summary").getJSONObject(0).getDouble("pricePerUnit") - (BazaarNotifier.bazaarDataRaw.getJSONObject(material).getJSONArray("sell_summary").getJSONObject(0).getDouble("pricePerUnit")) * 160;
          `

**Comment by curather** [comment]
[EnchantedCraftingHandler.zip](https://github.com/symt/BazaarNotifier/files/7655104/EnchantedCraftingHandler.zip)

Here is the complete file, couldn't upload the java file so I zipped it.

**Comment by symt** [comment]
@MagicPotatoooo

**Comment by symt** [comment]
I *think* this is fixed, but we'll see shortly.
