### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by tristan-f-r** [symt/BazaarNotifier#92]
```
java.lang.NumberFormatException: For input string: "142149 9572"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
    at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
    at java.lang.Float.parseFloat(Float.java:451)
    at dev.meyi.bn.modules.calc.BankCalculator.getPurseFromSidebar(BankCalculator.java:123)
```

Not sure when this is triggered.

**Comment by symt** [comment]
Something in Skytils does this
